### ISSUE TITLE
Asking for a documentation relative to docker usage

### ISSUE THREAD

**Issue by LaurentNoyon** [BaseXdb/basex#2413]
Hello dear BaseX team,

I'm new to BaseX and I'm trying to replace eXistDB with BaseX to test its performance in my web application.

I would like to run BaseX as a container and deploy a web GUI at myapplication.com/basex/

Currently I'm having trouble doing that.

Here is my docker-compose file : 
```
basex:
    image: basex/basexhttp:latest
    env_file:
        - ./../config/env/.env
    ports:
        - "8086:8984" # BaseX web GUI
    environment:
        BASEX_USER: "admin"
        BASEX_PASSWORD: "123"
    volumes:
        - basex_data:/srv/basex/data
    networks:
        - basex_network
    restart: always
```
And here is my .conf (I'm using apache)
```
<IfModule mod_ssl.c>
  <VirtualHost *:443>
    ... some rules
    ProxyPass /basex/ http://127.0.0.1:8086/
    ProxyPassReverse /basex/ http://127.0.0.1:8086/
    ...
  </VirtualHost>
</IfModule>
```
I have two problems : first, the password is not set, I have to user admin/admin to connect.
Secondly, when I access myapplication.com/basex/ I get "Service not found.", which means to me that basex is running and the proxy works, but I can't access its gui.

What am I doing wrong ? myapplication.com/basex/dba/ gives Service not found too.
myapplication.com/basex/rest/ works.

When I will be all good on this, I think it could be summarized in a nice documentation under a "Docker usage" section on the official website.

Thanks in advance for your help.
